export const COLLECTIONS = {
		users: "users",
		tracks: "tracks",
		artists: "artists",
		albums: "albums",
		playlists: "playlists",
		playlistItems: "playlist_items",
		likes: "likes",
		followedArtists: "followed_artists",
		followedPlaylists: "followed_playlists",
		savedAlbums: "saved_albums",
		searchEvents: "search_events",
		listeningEvents: "listening_events",
		recommendations: "recommendations_cache",
		recommendationHistory: "recommendations_history",
		radioSessions: "radio_sessions",
		radioQueueItems: "radio_queue_items",
		chartSnapshots: "chart_snapshots",
};
